name: Release

# Create a release on a tag push event
on:
  push:
    tags:
      - 'release/v*.*.*'

jobs:
  build:
    name: Basic java run
    uses: ./.github/workflows/base.yaml
    with:
      use-snapshots: false
    secrets:
      NANITE_TOKEN: ${{ secrets.nanite-token }}
