name: Release

# Create a release any commit to main
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Basic java run
    uses: ./.github/workflows/base.yaml
    with:
      use-snapshots: true
    secrets:
      saps-token: ${{ secrets.SAPS_TOKEN }}
